# In-Class Example
I am reading data from `AllPokemon.csv` into a data frame.

## Steps:
- Verify `Python` and `pip` are installed (`python --version` or `pip --version`).
- Install the `pandas` package with `pip install pandas` in the terminal. 
- Write the program (see below).

In [ ]:
python --version

# import pandas as pd

# df = pd.read_csv('AllPokemon.csv')
# df.head()

,Number,Name,Type1,Type2,Total,HP,Atk,Def,SpAtk,SpDef,Spd,Gen
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1
3,4,Charmander,Fire,,309,39,52,43,60,50,65,1
4,5,Charmeleon,Fire,,405,58,64,58,80,65,80,1

In [4]:
import pandas as pd, numpy as ny, sklearn as sl, seaborn as sb, statsmodels as sm, matplotlib as ml
print("Environment ready")

df = pd.read_csv('./AllPokemon.csv')
print(f"Extracted {len(df):,} rows and {len(df.columns)} columns")
df.head()

Environment ready
Extracted 1,045 rows and 12 columns

,Number,Name,Type1,Type2,Total,HP,Atk,Def,SpAtk,SpDef,Spd,Gen
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1
3,4,Charmander,Fire,,309,39,52,43,60,50,65,1
4,5,Charmeleon,Fire,,405,58,64,58,80,65,80,1

In [9]:
print(list(df['Type2']))

['Poison', 'Poison', 'Poison', ' ', ' ', 'Flying', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Poison', 'Poison', 'Poison', 'Flying', 'Flying', 'Flying', ' ', ' ', 'Flying', 'Flying', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Ground', ' ', ' ', 'Ground', ' ', ' ', ' ', ' ', 'Fairy', 'Fairy', 'Flying', 'Flying', 'Poison', 'Poison', 'Poison', 'Grass', 'Grass', 'Poison', 'Poison', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Fighting', ' ', ' ', ' ', ' ', ' ', ' ', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Ground', 'Ground', 'Ground', ' ', ' ', 'Psychic', 'Psychic', 'Steel', 'Steel', 'Flying', 'Flying', 'Flying', ' ', 'Ice', ' ', ' ', ' ', 'Ice', 'Poison', 'Poison', 'Poison', 'Ground', ' ', ' ', ' ', ' ', ' ', ' ', 'Psychic', 'Psychic', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Rock', 'Rock', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Psychic', 'Fairy', 'Flying', 'Psychic', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Ice', ' ', ' ', ' ', ' ', ' ', ' ', 'Water', 'Water', 'Water', 'Water', 'Flying', ' ', 'Flying', 'Flying', 'Flying', ' ', ' ', 'Flying', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Flying', 'Flying', 'Flying', 'Poison', 'Poison', 'Flying', 'Electric', 'Electric', ' ', ' ', 'Fairy', ' ', 'Flying', 'Flying', 'Flying', ' ', ' ', ' ', ' ', 'Fairy', 'Fairy', ' ', ' ', 'Flying', 'Flying', 'Flying', ' ', ' ', ' ', 'Flying', 'Ground', 'Ground', ' ', ' ', 'Flying', 'Psychic', ' ', ' ', ' ', 'Psychic', ' ', 'Steel', ' ', 'Flying', 'Ground', ' ', ' ', 'Poison', 'Steel', 'Rock', 'Fighting', 'Ice', ' ', ' ', ' ', 'Rock', 'Ground', 'Ground', 'Rock', ' ', ' ', 'Flying', 'Flying', 'Flying', 'Fire', 'Fire', 'Dragon', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Psychic', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Ground', 'Ground', 'Dark', 'Flying', 'Flying', 'Grass', ' ', ' ', ' ', ' ', 'Fighting', 'Fighting', ' ', 'Ground', 'Ground', ' ', ' ', ' ', ' ', ' ', ' ', 'Flying', ' ', 'Poison', 'Grass', 'Grass', 'Grass', ' ', 'Dark', 'Dark', 'Flying', 'Flying', 'Flying', 'Flying', 'Fairy', 'Fairy', 'Fairy', 'Water', 'Flying', ' ', 'Fighting', ' ', ' ', ' ', 'Ground', 'Flying', 'Ghost', ' ', ' ', ' ', ' ', ' ', 'Fairy', ' ', ' ', ' ', 'Ghost', 'Fairy', 'Rock', 'Rock', 'Rock', 'Psychic', 'Psychic', ' ', ' ', ' ', ' ', ' ', ' ', 'Poison', ' ', ' ', 'Dark', 'Dark', ' ', ' ', 'Ground', 'Ground', ' ', ' ', ' ', ' ', ' ', 'Dragon', 'Dragon', ' ', 'Dark', 'Flying', 'Flying', ' ', ' ', 'Psychic', 'Psychic', 'Ground', 'Ground', ' ', 'Dark', 'Psychic', 'Psychic', 'Grass', 'Grass', 'Bug', 'Bug', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Flying', ' ', ' ', ' ', ' ', ' ', 'Water', 'Water', 'Water', ' ', ' ', ' ', 'Rock', ' ', ' ', ' ', 'Flying', 'Psychic', 'Psychic', 'Psychic', ' ', ' ', ' ', 'Psychic', 'Psychic', ' ', ' ', 'Flying', 'Psychic', ' ', ' ', ' ', ' ', ' ', ' ', 'Ground', ' ', 'Fighting', 'Fighting', ' ', ' ', 'Steel', 'Flying', 'Flying', 'Flying', ' ', 'Water', ' ', ' ', ' ', ' ', ' ', 'Poison', 'Poison', ' ', ' ', 'Steel', 'Steel', ' ', 'Grass', 'Ground', 'Steel', 'Flying', 'Flying', 'Flying', ' ', ' ', ' ', ' ', ' ', ' ', 'Ground', ' ', 'Flying', 'Flying', ' ', ' ', ' ', 'Flying', ' ', ' ', ' ', 'Dark', 'Dark', 'Psychic', 'Psychic', ' ', 'Fairy', ' ', 'Flying', 'Dark', 'Ground', 'Ground', 'Ground', ' ', ' ', 'Steel', ' ', ' ', 'Bug', 'Dark', 'Fighting', 'Fighting', ' ', ' ', ' ', 'Flying', 'Ice', 'Ice', 'Ice', 'Steel', ' ', 'Rock', ' ', ' ', ' ', 'Flying', 'Flying', ' ', ' ', 'Flying', 'Ground', ' ', 'Fighting', 'Steel', ' ', 'Ghost', 'Ghost', 'Fire', 'Water', 'Ice', 'Flying', 'Grass', ' ', ' ', ' ', 'Dragon', 'Dragon', 'Steel', ' ', 'Dragon', 'Dragon', ' ', ' ', ' ', ' ', ' ', 'Flying', ' ', 'Fire', ' ', ' ', ' ', ' ', 'Fighting', 'Fighting', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Flying', 'Flying', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Flying', ' ', 'Steel', ' ', ' ', ' ', ' ', ' ', 'Ground', 'Ground', ' ', ' ', 'Grass', 'Grass', 'Grass', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', ' ', ' ', ' ', ' ', 'Dark', 'Dark', 'Dark', ' ', ' ', 'Psychic', ' ', 'Rock', 'Rock', 'Fighting', 'Fighting', 'Flying', ' ', ' ', 'Rock', 'Rock', 'Flying', 'Flying', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Flying', 'Flying', ' ', ' ', ' ', 'Grass', 'Grass', 'Flying', ' ', 'Steel', 'Poison', 'Poison', 'Ghost', 'Ghost', ' ', 'Electric', 'Electric', 'Steel', 'Steel', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Fire', 'Fire', 'Fire', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Electric', ' ', ' ', ' ', 'Ghost', 'Ghost', 'Steel', 'Steel', ' ', 'Flying', 'Flying', 'Flying', 'Flying', ' ', 'Steel', 'Dragon', 'Dragon', 'Dragon', 'Fire', 'Fire', 'Fighting', 'Fighting', 'Fighting', ' ', ' ', 'Flying', 'Flying', 'Fire', 'Electric', 'Flying', 'Flying', 'Ice', 'Ice', 'Ice', 'Fighting', 'Fighting', 'Psychic', 'Fighting', 'Steel', 'Poison', 'Dragon', 'Flying', ' ', 'Poison', 'Flying', ' ', 'Psychic', 'Poison', ' ', 'Flying', 'Dark', 'Flying', 'Fighting', ' ', 'Dragon', 'Ground', 'Steel', 'Fighting', 'Fire', 'Dark', 'Dragon', 'Fighting', 'Ground', 'Fairy', 'Ghost', 'Fairy', ' ', 'Psychic', ' ', 'Dark', 'Ground', 'Fairy', ' ', ' ', ' ', 'Flying', 'Psychic', 'Psychic', 'Psychic', ' ', 'Fire', 'Flying', 'Fighting', 'Ground', 'Steel', 'Ice', 'Fighting', 'Fairy', ' ', ' ', 'Fighting', ' ', ' ', 'Psychic', ' ', ' ', 'Dark', ' ', 'Ground', 'Flying', 'Flying', 'Flying', ' ', ' ', 'Flying', 'Normal', 'Normal', ' ', ' ', ' ', ' ', ' ', ' ', 'Dark', ' ', ' ', ' ', ' ', 'Ghost', 'Ghost', 'Ghost', 'Ghost', ' ', ' ', ' ', ' ', 'Psychic', 'Psychic', 'Water', 'Water', 'Water', 'Dragon', ' ', ' ', 'Normal', 'Normal', 'Dragon', 'Dragon', 'Ice', 'Ice', ' ', 'Flying', 'Fairy', 'Fairy', ' ', ' ', ' ', 'Fairy', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', ' ', ' ', 'Dragon', 'Dragon', ' ', 'Flying', 'Ground', 'Fairy', 'Fairy', 'Ghost', 'Dark', 'Water', 'Normal', 'Normal', ' ', 'Psychic', 'Steel', 'Steel', ' ', 'Fairy', 'Steel', 'Steel', ' ', ' ', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Dragon', 'Ghost', ' ', 'Dark', 'Ground', 'Ground', 'Flying', 'Flying', 'Ghost', ' ', ' ', 'Dark', ' ', ' ', 'Fairy', 'Flying', 'Flying', 'Flying', ' ', ' ', ' ', 'Electric', 'Electric', ' ', 'Ice', 'Flying', 'Flying', 'Flying', 'Flying', 'Fairy', 'Fairy', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Water', 'Water', ' ', ' ', 'Bug', 'Bug', ' ', ' ', 'Fairy', 'Fairy', 'Fire', 'Fire', 'Fighting', 'Fighting', ' ', ' ', ' ', ' ', 'Psychic', ' ', 'Water', 'Water', 'Ground', 'Ground', ' ', ' ', ' ', 'Flying', 'Flying', ' ', 'Dragon', 'Steel', 'Fairy', 'Psychic', 'Dragon', 'Grass', ' ', 'Fighting', 'Fighting', 'Fairy', 'Fairy', 'Fairy', 'Fairy', ' ', ' ', 'Steel', 'Ghost', 'Poison', 'Fighting', 'Fighting', ' ', 'Flying', 'Steel', 'Dragon', ' ', 'Steel', 'Ghost', 'Dragon', 'Fairy', 'Ghost', ' ', 'Dragon', 'Steel', 'Ghost', ' ', ' ', ' ', ' ', ' ', 'Fairy', ' ', 'Psychic', ' ', 'Fairy', 'Ice', 'Flying', 'Flying', 'Flying', 'Psychic', ' ', 'Normal', 'Normal', ' ', ' ', 'Fire', 'Ghost', 'Steel', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Steel', ' ', 'Psychic', 'Psychic', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Rock', ' ', ' ', ' ', 'Fire', 'Fire', 'Dragon', 'Dragon', 'Dragon', ' ', ' ', 'Water', ' ', ' ', 'Poison', 'Poison', 'Poison', 'Bug', 'Bug', ' ', ' ', ' ', ' ', ' ', ' ', 'Fairy', 'Fairy', 'Fairy', 'Fairy', 'Normal', ' ', ' ', ' ', 'Ice', 'Ghost', ' ', ' ', ' ', ' ', 'Bug', 'Bug', ' ', ' ', ' ', 'Normal', 'Normal', 'Dark', 'Dark', ' ', ' ', 'Dragon', 'Ice', 'Dragon', 'Ice', 'Dragon', 'Ghost', 'Ghost', 'Ghost', 'Steel', ' ', 'Steel', ' ', 'Dragon', 'Dragon', ' ', 'Dark', 'Water', 'Grass', ' ', ' ', ' ', ' ', 'Grass', 'Ice', 'Ghost']